### ISSUE TITLE
google analytics for routes

### ISSUE THREAD

**Issue by yipcma** [Polymer/shop#101]
The current google analytics only gives / for each visitors. I'm very curious how we may see all the different routes that the user visits show up?

Thank you very much for helping.

**Comment by yipcma** [comment]
solved my own problem (partially):

use observer on route.*

However, when i call window.ga(...), it works but the browser console complains that window.ga is not a function. why is that?

**Comment by frankiefu** [comment]
Seems like you might be calling `window.ga(...)` before `<shop-analytics>` is loaded and upgraded.

**Comment by frankiefu** [comment]
Closing this. If you are still having issue please reopen it.
