### ISSUE TITLE
404 not loaded/renderered

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/shop#106]
Go at: https://shop.polymer-project.org/sdfsdf

Nothing happens - I would expect a 404 page to show up, right?

**Comment by tookit** [comment]
yes, this should fire not-found event, when importHref error happens

**Comment by TimvdLippe** [comment]
It seems that after #81 was merged no new version was deployed.

**Comment by ebidel** [comment]
@frankiefu @blasten @keanulee do we need to deploy a new version?

FWIW, https://shop.polymer-project.org/ is down atm.

**Comment by frankiefu** [comment]
Yes, I have asked to get a new deploy.  I think @usergenic and @garlicnation are working on it.

**Comment by frankiefu** [comment]
Should be all good now.

**Comment by frankiefu** [comment]
There was an issue with the deploy and we had to roll it back.  The team is looking into it and will post an update when we figure it out.
