### ISSUE TITLE
2.0 Preview Branch cannot be built

### ISSUE THREAD

**Issue by etimberg** [Polymer/shop#109]
I tried using the `2.0-preview` branch to see if I could get Polymer-CLI to correctly bundle the shop demo. It does not appear to work and when loaded, an error that `Polymer` is undefined is received. 

## Reproduce
To reproduce this issue, I did the following (assuming Polymer-CLI and bower already installed)
1. `git clone https://github.com/Polymer/shop.git`
2. `cd shop`
3. `git checkout 2.0-preview`
4. `bower install`
5. `polymer build`
6. `polymer serve build/bundled`
7. Open `localhost:8000` in Chrome. 
8. Open the debug console and notice the error.
![polymer error](https://cloud.githubusercontent.com/assets/6757853/22026172/0a09a5fc-dc9e-11e6-87ff-f3f93b16791c.png)

## Workaround
The shop demo works correctly if you just run `polymer serve` and don't use the bundled version. 

## Versions Used
Polymer-CLI: `0.18.0-alpha.8`
Node: `6.9.2`
Browser: `Chrome 55.0.2883.87`

**Comment by frankiefu** [comment]
It should work with `polymer-cli: 0.18.0-pre.13`

**Comment by frankiefu** [comment]
Please install the `@next` version of `polymer-cli`: https://www.polymer-project.org/2.0/docs/tools/polymer-cli
