### ISSUE TITLE
shop-detail calls _computeItem before _computeCategory sometimes getting an old category

### ISSUE THREAD

**Issue by gregroyal** [Polymer/shop#113]
The shop-detail pages requests the item before the category, which if its a new category causes the item lookup to fail.

The quick workaround is to remove `this.fire('show-invalid-url-warning');` in ` _computeItem `.
Only downside is if someone really does type a bad url, you wont get an error page

**Comment by frankiefu** [comment]
Is the issue still reproducible in the latest, like in https://shop.polymer-project.org? If so could you provide the steps to reproduce the issue?

**Comment by gregroyal** [comment]
I dont maintain that project really anymore so I'm just going to close this issue since i dont have time to research more. I worked around it at the time
