### ISSUE TITLE
Use of webcomponents.js on Polymer 2.0 Preview branch

### ISSUE THREAD

**Issue by alkzoupas** [Polymer/shop#127]
Hi,

We have been working with the Polymer 2.0 Preview version of Shop and have noticed that there has been a change in the way webcomponents.js is being used compared to the released Polymer 1.0 version.

Specifically we are seeing that "shop-app.html" is not any more asynchronously being loaded and also "webcomponents-loader.js" is being used instead of "webcomponents-lite.js" (for reference https://github.com/Polymer/shop/blob/2.0-preview-class/index.html). 

This approach actually seems to be worse than the previous one and the application is being severely dinged on the "first meaningful paint" Lighthouse metric.
Was there some specific reason why this approach was followed on Polymer 2.0 and is this going to be the suggested approach for Polymer 2.0?

Thank you in advance!

Alkis

**Comment by frankiefu** [comment]
There was an [issue](https://github.com/webcomponents/shadycss/pull/96) in ShadyCSS causing async loading to fail. Since it's fixed now we just updated to import async: https://github.com/webcomponents/shadycss/pull/96

Thanks for the report!

**Comment by frankiefu** [comment]
Fixed in https://github.com/Polymer/shop/pull/128
