### ISSUE TITLE
How to add page Description dynamically

### ISSUE THREAD

**Issue by NaqashPixy** [Polymer/shop#133]
How you are adding description dynamically to shop app pages  
as it shown by google 
 https://www.google.com/#q=site:https://shop.polymer-project.org
i also want to do so 
but in my case same description is shown by google for every indexed page
https://www.google.com/#q=site:https://polymerjs.io

in Shop app prject i see description attribute in .json file but it seems like that is not used in any element/page

**Comment by frankiefu** [comment]
The important bit is to follow the existing [web master guidelines](https://support.google.com/webmasters/answer/66359), and include things like canonical links, use `<a href>`, correct meta data, etc.
