### ISSUE TITLE
How to run Polymer shop in Github page?

### ISSUE THREAD

**Issue by vanloc0301** [Polymer/shop#134]
I show all source write with HTML.

Have any method to run `shop` with Github page like [Hugo](https://github.com/gohugoio/hugo)?

**Comment by keanulee** [comment]
GitHub Pages doesn't support URL rewrites, which are required to support single page apps like Shop. Consider using another service such as [Firebase Hosting](https://www.polymer-project.org/2.0/start/toolbox/deploy#deploy-with-firebase).
