### ISSUE TITLE
Shop upgraded in Polymer 2.0 doesn't render in Google Search Console & Page Speed

### ISSUE THREAD

**Issue by TBLOREAL** [Polymer/shop#135]
Since the shop used Polymer 2.0 Google Search Console doesn't render the page when we "fetch as google and render". We see a blanck page.

Same problem with Page Speed, the render is a blanck page.

Shop with Polymer 2.0 : 
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fshop-pwa.appspot.com%2F&tab=desktop

Shop with Polymer 1.X : 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fshop.polymer-project.org%2F

Do you know why?

**Comment by TBLOREAL** [comment]
In addition here the Shop init served just after : 
    git clone https://github.com/Polymer/shop.git

https://shop-init.appspot.com/

Google Page Speed issue : 
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fshop-init.appspot.com%2F&tab=mobile

Same Issue with the future Googlebot Smartphone : 
https://search.google.com/test/mobile-friendly?id=6gHmUQiMJNm9ET-yeRxVqA

Thanks

Regards

**Comment by frankiefu** [comment]
This is fixed in https://github.com/webcomponents/custom-elements/pull/107 and https://github.com/Polymer/shop/pull/140.

**Comment by TBLOREAL** [comment]
@frankiefu : 
Thanks, so for the moment in order to solve the problem we have to use ES5 till google bot can manage ES6?

**NB :** 
For other who had the problem. It solved with ES5 build & "webcomponentsjs": "^v1.0.2"
In polymer.json add an es5 build : 
...
  {
      "name":"es5-bundled",
      "preset": "es6-bundled",
       "js": {
        "minify": true,
        "compile": true
       }
    }
...

This ES5 build is deployed here : 
https://20170808t111540-dot-shop-init.appspot.com/

Page Speed - ES5 build : Problem solved
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2F20170808t111540-dot-shop-init.appspot.com%2F&tab=mobile

Page Speed - ES6 Bundle Build : Problem still here
https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2F20170808t110933-dot-shop-init.appspot.com%2F

The ES6 build is deployed here : 
https://20170808t110933-dot-shop-init.appspot.com/
