### ISSUE TITLE
Back end  Admin UI console 

### ISSUE THREAD

**Issue by augmen** [Polymer/shop#138]
Great app polymer . Where to find the backend admin UI for managing the shop orders ? i am asking back end like magento / spree ? Thanks

**Comment by georlitz** [comment]
I don't believe they've created a fully-fledged e-commerce application like magento here. More like a simple demo for what's possible for a shop front-end.

That being said, you can mostly eliminate the need for a backend by integrating this with firebase (authentication, database, hosting, and endpoints) and stripe (payments, order fulfillment).  Other web technologies with APIs would work as well. Check out this Google I/O video where they create a Woot-like app by integrating firebase and stripe: https://youtu.be/G-MBeEW92v4. That was very helpful for myself in doing something like what you're asking.

**Comment by frankiefu** [comment]
As @georlitz mentioned, this is out of the scope for this project. And thanks @georlitz for the video!

**Comment by mariojfduarte** [comment]
Is there any tutorial for implementing stripe ?
