### ISSUE TITLE
Mobile browser address bar doesn't hide/collapse

### ISSUE THREAD

**Issue by Royedc4** [Polymer/shop#139]
Hey, Polymer Community, I found an error over the browser behaviour of hiding/collapsing address bar. It works when you land into the app, but this behaviour stops working after navigating to another page, as described next:

#### Error

![onlyproblem](https://user-images.githubusercontent.com/1709472/28804854-ee05f0ec-7633-11e7-95b2-401853bff172.gif)

#### Expected Behaviour

![expected](https://user-images.githubusercontent.com/1709472/28794278-cbc8d75e-7603-11e7-9d6a-f23465f73805.gif)

#### Browser

- [x] Chrome
- [x] Safari

#### OS

- [x] iOS

In terms of space, my app requires the browser to use this normal behaviour of hiding the address bar. I could force this behaviour by reloading the page but this affects the PWA perception.

Maybe the issue is related to app-header-layout and iron-pages, I've tested in various ways and I notice that this behaviour it's present when using them.

Any comments or ideas may be helpful, as debugging in iOS is not straightforward Thanks!

**Comment by frankiefu** [comment]
I am seeing the issue in other PWA's like those demo apps in https://hnpwa.com/
This seems like a bug in Chrome on iOS: https://bugs.chromium.org/p/chromium/issues/detail?id=751664
