### ISSUE TITLE
Polymer + Cordova 

### ISSUE THREAD

**Issue by augmen** [Polymer/shop#141]
i have tried to install the polymer shop app in `www` folder and add the polymer app `index.html` file to cordova `www` `index.html`. which now ,took like this 
`<!DOCTYPE html>

<html>
    <head>
      <meta charset="utf-8">
      <base href="/">
        
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">

    
        <title>SHOP</title>

        <link rel="shortcut icon" sizes="32x32" href="images/shop-icon-32.png">

        <meta name="theme-color" content="#fff">
        <link rel="manifest" href="manifest.json">
        <style>

          body {
            margin: 0;
            font-family: 'Roboto', 'Noto', sans-serif;
            font-size: 13px;
            line-height: 1.5;
            min-height: 100vh;
          }

          /* styling for render while resources are loading */
          shop-app[unresolved] {
            display: block;
            min-height: 101vh;
            line-height: 68px;
            text-align: center;
            font-size: 16px;
            font-weight: 600;
            letter-spacing: 0.3em;
            color: #202020;
            padding: 0 16px;
            overflow: visible;
          }

        </style>

    </head>
    <body>
      <shop-app unresolved>SHOP</shop-app>

      <script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
      <link rel="import" href="src/shop-app.html">

      <script>
        window.performance && performance.mark && performance.mark('index.html');
      </script>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>
`

then run the `cordova run android`
but the app docent show the exact app .
![screen shot 2017-08-07 at 20 07 30](https://user-images.githubusercontent.com/11497036/29031498-1555a7e6-7bac-11e7-83ab-bb43e05c637b.png)

Please guide

**Comment by Masatoshi** [comment]
It's not fault of shop repo.
Just put following.

<base href="file:///android_asset/www/">

**Comment by frankiefu** [comment]
Thanks @Masatoshi for the answer.
