### ISSUE TITLE
Creating a new page

### ISSUE THREAD

**Issue by chris1000** [Polymer/shop#148]
I've been messing around with the Shop template trying to make something similar and I was wondering if someone could help me make a simple About Us page. I've made a "aboutus.html" file and put it in src/ but I can't figure out how to get it to work. Every time I try to navigate to it in Chrome I get the error 404 page. 

Any help would be amazing, thank you!

**Comment by keanulee** [comment]
I actually have a git branch lying around that shows how to add an about page - https://github.com/Polymer/shop/compare/about-shop. Hope that helps.

**Comment by chris1000** [comment]
It did thank you so much! Now I just need to figure out how to make a dummy "My Account" page and I'll be set.

**Comment by frankiefu** [comment]
There is also a guide in the Polymer Docs site on how to create a new page:
https://www.polymer-project.org/2.0/start/toolbox/create-a-page

The doc is for starter template but the same concept can apply to Shop as well. And with @keanulee branch that should give you enough idea.
