### ISSUE TITLE
ShopCategoryData.categories is read only

### ISSUE THREAD

**Issue by flatmax** [Polymer/shop#149]
Hi there,

Great app ... we are wanting to use it. We have come across the problem that ShopCategoryData.categories is read only.

For that reason, we can't overload the class and set ShopCategoryData.categories to what we need for our shop. We actually have to edit the shop-category-data.html file to put our shop categories into the app.

Anyone got workarounds for this ? We can't think of any beyond editing shop-category-data.html

Matt

**Comment by jsilvermist** [comment]
If you have a read-only property called `categoryData`, it can be set using:
```
this._setCategoryData(newVal);
```

This is the pattern used to set a read-only property, for more info, see:
[finding link, will edit]

**Comment by frankiefu** [comment]
Thanks @jsilvermist for the answer.
