### ISSUE TITLE
Doesn't work on Internet Explorer 11

### ISSUE THREAD

**Issue by hamzahrmalik** [Polymer/shop#157]
I cannot get the demo to work on IE 11 build 11.786.15063.0 on Windows 10. To ensure it's not an error in the build system, i ran the demo at shop.polymer-project.org and got the following errors:

![image](https://user-images.githubusercontent.com/6820175/34040895-af0a4706-e18d-11e7-86b0-a6cd27f68f29.png)

The same error occurs when I try to build it myself using es5 bundled or unbundled both. Using the _polymer serve_ command works fine

UPDATE

It does work on IE 11.125.16299.0 on a friends computer, also on Windows 10

**Comment by azakus** [comment]
Hmm, in the screenshot here it looks like you have some IE back compat mode on? If your browser is in IE <11 mode, that could be the issue.

**Comment by hamzahrmalik** [comment]
@azakus good point i didn't spot that, it says its because "display intranet sites in compatibility..." but this isn't an intranet
