### ISSUE TITLE
[enhancement]Using Payment Request API

### ISSUE THREAD

**Issue by chwzr** [Polymer/shop#159]
Maybe providing  two Buttons on the products page: one which adds to cart (normal checkout process) and one which says "buy instant"... and then trigger the payment request api with that to direct buy one element.

**Comment by spyhole** [comment]
YES!

**Comment by Mtsmachado8** [comment]
Yes!! Couldnt find the src of payment request with polymer shop(showed in Google Io). If someone knows post link please.

**Comment by keanulee** [comment]
Maybe it's this fork? https://github.com/agektmr/shop/ (not maintained by the Polymer team)

There's also the [credential-payment-api branch](https://github.com/Polymer/shop/compare/credential-payment-api) on this repo, though that branch isn't kept up to date.

**Comment by Mtsmachado8** [comment]
That one!! Thanks 😁

**Comment by keanulee** [comment]
Closing - not interested in having these changes in the main `master` branch, but will keep the [`credential-payment-api`](https://github.com/Polymer/shop/compare/credential-payment-api) branch around so users can see the changes required (see my opinion at https://github.com/Polymer/shop/pull/91#issuecomment-331957032).
