### ISSUE TITLE
Unable to understand how SEO is taken care of

### ISSUE THREAD

**Issue by bramu** [Polymer/shop#161]
Can someone please explain me how the SEO aspect of polymer project is taken care of?  We are thinking of considering polymer for our next big application and I am worried end of hit by SEO.

**Comment by keanulee** [comment]
My colleague @samuelli [wrote a couple Medium posts](https://medium.com/@samdotli) about client-side rendering (such as Polymer) and SEO which may be helpful. Shop uses [prpl-server-node](https://github.com/Polymer/prpl-server-node#rendering-for-bots) to proxy requests from bots to a headless chrome rendering server.

**Comment by bramu** [comment]
Thanks for directing to the right information.
