### ISSUE TITLE
Showing project folder structure on local if file is not found in polymer project.

### ISSUE THREAD

**Issue by mayakharat** [Polymer/shop#168]
When I navigate "https://shop.polymer-project.org/unknown.txt", I am getting error "not found". But when i do the same in my local, I am getting error "ENOENT: no such file or directory, stat 'D:\user_directory\Polymer\ShopApp\unknown.txt". My requirement is to not to show my folder structure and show only "not found"
![error](https://user-images.githubusercontent.com/36636482/36385876-92e2f488-1559-11e8-9423-62c8726d5aa8.png)

![error2](https://user-images.githubusercontent.com/36636482/36386134-5e24bbd6-155a-11e8-81e0-ecaab286d888.png)

**Comment by keanulee** [comment]
What local web server are you using? If you're using `polymer serve`, that's a development server so showing directory structure is expected. We use prpl-server for deployment which doesn't show directory structure.
