### ISSUE TITLE
SEO, Schema, Structured Data

### ISSUE THREAD

**Issue by Sourav-21** [Polymer/shop#170]
How to add JSON-LD Structured Data to polymer app for SEO?

**Comment by keanulee** [comment]
We do client-side rendering of `<meta>` elements in `<head>`:

https://github.com/Polymer/shop/blob/d77b1e1a07d51addd37351061d3b7833259cb32e/src/shop-app.html#L473-L481

You could render JSON-LD in the same place instead. Note that you may need a server-side rendering service to support all bots - see https://github.com/Polymer/shop/issues/161#issuecomment-363521338.
