### ISSUE TITLE
is this still being developed? and whats the backend?

### ISSUE THREAD

**Issue by seansan** [Polymer/shop#171]
is this still being developed? and whats the backend?

maybe add to readme

sounds quite interesting

**Comment by samcarecho** [comment]
There is no Backend and never will be. 
From what I'm following since the launch of the project, the goal is to demo the usage of Polymer.

**Comment by frankiefu** [comment]
@samcarecho is correct. Shop is a demo for showing how to build PWA using Polymer. We will try to update the app when a new version of Polymer is released. You can find Polymer 3.0 version of Shop in the [3.0 branch](https://github.com/Polymer/shop/tree/3.0).
