### ISSUE TITLE
Safari 4 by 4 grid

### ISSUE THREAD

**Issue by chris1000** [Polymer/shop#174]
I'm trying to make the home screen a 4 x 4 grid (Like in Firefox (Left side) and all browsers besides Safari work, for some reason safari won't display a 4x4 grid any help would be extremely appreciated.

Screenshot 1: Left Side - Firefox doing what I'm trying to achieve, Right side - Safari not working
Screenshot 2: Code used to achieve the 4x4 grid in Firefox and Chrome
![screen shot 2018-04-03 at 12 23 56 pm](https://user-images.githubusercontent.com/7182759/38262030-05bad5d2-373a-11e8-9d65-229922d175fe.png)
![screen shot 2018-04-03 at 12 24 44 pm](https://user-images.githubusercontent.com/7182759/38262061-1d436052-373a-11e8-8f88-356981990802.png)

**Comment by keanulee** [comment]
I think there's an issue with `:nth-of-type()` selectors in Safari Shadow DOM (trying to find the bug, will update if I do). If all the items are the same though, you can just apply those styles on `.item` instead.

**Comment by keanulee** [comment]
Couldn't find the WebKit bug so I just filed a new one https://bugs.webkit.org/show_bug.cgi?id=184273
