### ISSUE TITLE
Firefox - does not work at all

### ISSUE THREAD

**Issue by maxfromua** [Polymer/shop#178]
<img width="1440" alt="screenshot 2018-05-03 14 12 38" src="https://user-images.githubusercontent.com/9142824/39573493-17df554e-4edc-11e8-9699-f31d37520729.png">
Despite the fact that PWA Starter Kit works fine in FF, I see the blank screen on your shop.
FF 59.0.2 (64-bit)  
macOS 10.13.4   
MacBook Pro 15 2015  
  
In Safari and Chrome works fine

**Comment by keanulee** [comment]
Just updated the demo at https://lit-element-dot-polymer-shop.appspot.com/, should be working on Firefox now. Other browsers may still be broken by the [known issues listed in pwa-starter-kit](https://github.com/Polymer/pwa-starter-kit#known-issues).

**Comment by abdonrd** [comment]
It doesn't work for me in Firefox 57:

<img width="1319" alt="screen shot 2018-05-04 at 00 11 29" src="https://user-images.githubusercontent.com/1007051/39605233-cdcea0be-4f2f-11e8-903b-75718277812a.png">

**Comment by keanulee** [comment]
Generally our support matrix would exclude Firefox 57 (58 and 59 are the [latest 2 versions](https://www.polymer-project.org/2.0/docs/browsers)), but looking at the line/column of shop-app.js it looks like an object spread operator so it will be fixed once https://github.com/Polymer/tools/issues/173 is released.

**Comment by maxfromua** [comment]
Thank you, works now.
Great work, guys!

**Comment by keanulee** [comment]
FYI I updated https://lit-element-dot-polymer-shop.appspot.com/ again with the object spread transform - it might in FF 57 now.

**Comment by abdonrd** [comment]
Yay! It works now, thanks @keanulee!
