### ISSUE TITLE
The Hyperlink in the footer section is linked to an older version of Polymer toolbox.

### ISSUE THREAD

**Issue by pereiraryan** [Polymer/shop#183]
The current link on the Polymer app is linked to an older version of Polymer toolbox. which is 1.0,
Shouldn't it be linked to the new toolbox which is https://www.polymer-project.org/3.0/toolbox/  is the app being built on 1.0 or is it on 3.0?

**Comment by keanulee** [comment]
The currently deployed site is 2.0, so if anything it should point to that. The footer in the 3.0 branch has been updated.
