### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by tejaskatariya** [Polymer/shop#194]
I am trying to add manifest.json and click add to homescreen option. It is always giving me
Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest.

I am trying this locally and using polymer 2.0

Manifest.json looks something like

{
  "name": "fgh",
  "short_name": "ggg",
  "theme_color": "#3f51b5",
  "background_color": "#f8ea48",
  "display": "standalone",
  "start_url": "/",
  "icons": [
    {
      "src": "images/manifest/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "images/manifest/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "splash_pages": null
}

Any help would be appreciated.

**Comment by jsilvermist** [comment]
Are you generating a service worker from the polymer-cli? Does the service worker get registered in your entrypoint?

**Comment by keanulee** [comment]
Is the site being served with https:// (or localhost) to allow SW registration? Check Chrome devtools > Application > Service Workers panel to make sure it's registered.

![image](https://user-images.githubusercontent.com/1319720/46179623-01ace080-c271-11e8-85d5-8e6ea1c5f8e3.png)
