### ISSUE TITLE
What happened to webpack branch?

### ISSUE THREAD

**Issue by quetzalsly** [Polymer/shop#220]
I was using the webpack lit-element branch for my project to learn webpack + polymer, but suddenly that branch is now inactive? what happened? it seemed to work fine.

**Comment by keanulee** [comment]
[Inactive (or "stale") branches](https://github.com/Polymer/shop/branches/stale) are branches that were made a while ago and haven't been kept up to date with changes in the `master` branch. They may still work, but they may have merge conflicts with the latest code.
