### ISSUE TITLE
Error in Shop app -- Missing File

### ISSUE THREAD

**Issue by samgithub-duplicate** [Polymer/shop#23]
![shoperror](https://cloud.githubusercontent.com/assets/731590/15431256/f8a7633e-1e76-11e6-86f4-338bf9042380.png)
I'm getting a strange error

http://localhost:63618/src/shop-index.html.html 
Failed to load resource: the server responded with a status of 404 (Not Found)
(Error found in util.html)

a) Notice the 2 html file types
b) the file shop-index does not exist anywhere in the app.

**Comment by frankiefu** [comment]
How did you serve the app?  Did you use [polymer-cli](https://github.com/Polymer/polymer-cli) and follow the [README](https://github.com/Polymer/shop#shop) instruction?

**Comment by frankiefu** [comment]
We have fixed a few issues in [polymer-cli](https://github.com/Polymer/polymer-cli).  This may be related to the issues already fixed.  Please try again and file the issue in [polymer-cli](https://github.com/Polymer/polymer-cli) if you are still having issue serving the app.
