### ISSUE TITLE
Windows polymer serve build/bundled ERRORS

### ISSUE THREAD

**Issue by kilombo** [Polymer/shop#28]
When i execute **polymer serve build/bundled** i have these errors:
**index.html_script_0.js:1 Uncaught SyntaxError: Unexpected token <**

![screenshot-localhost 8080 2016-05-22 19-37-52](https://cloud.githubusercontent.com/assets/3757913/15455442/cc6c4d0e-2054-11e6-90f6-119698d4e5a3.png)

**Comment by frankiefu** [comment]
There are a few window build issues in polymer-cli.  Could you file the issue there?
https://github.com/Polymer/polymer-cli/issues

**Comment by kilombo** [comment]
Originally i was writing on polymer-cli, but i supposed it was a shop issue.

Done:
https://github.com/Polymer/polymer-cli/issues/191

Thanks @frankiefu !

**Comment by frankiefu** [comment]
Thanks @kilombo
