### ISSUE TITLE
Save scroll position on product list

### ISSUE THREAD

**Issue by tjsavage** [Polymer/shop#30]
Repro:

1) Load shop
2) Go to Mens Outerwear
3) Scroll to the bottom
4) Select the Jacquard-Knit Full-Zip Fleece
5) Go back

Notice that this places you back at the top of the list. Ideally scroll position would be saved, and you'd be back at the bottom of the list.

**Comment by abdonrd** [comment]
It seems work for the `app-layout/app-scrollpos-control`.
