### ISSUE TITLE
Do we still need to use vulcanize? 

### ISSUE THREAD

**Issue by iSuslov** [Polymer/shop#31]
I see that shop app uses the trick called `lazy loading` :) Is it possible to use lazy loading with vulcanize? I guess no, so do we still need it?

**Comment by frankiefu** [comment]
Yes.  We are still using Vulcanize for the bundled build.  And the app-shell will lazy load the bundled fragments.  For more info about build, please go to:
https://github.com/Polymer/polymer-cli
and
https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build
