### ISSUE TITLE
Click error in the paper-icon-button

### ISSUE THREAD

**Issue by abdonrd** [Polymer/shop#33]
I record a GIF to show the problem:

![shop-paper-icon-button](https://cloud.githubusercontent.com/assets/1007051/15559345/9ddcb214-22e1-11e6-9f76-f7fa0d32b3d1.gif)

If I click in the border icon zone, it doesn't work. If I click in the icon, it works.

**Comment by frankiefu** [comment]
Sounds like a general issue in `paper-icon-button` and `tap` gesture, and not specifically in the Shop app.

**Comment by abdonrd** [comment]
You are probably right. 😕

**Comment by jfrazzano** [comment]
First, awesome job. Thanks again Frankie. Up until this week was still using the dual drawer model you offered (full swipe scroll added). 

On buttons, noticed a "slow" anchor trigger on the modal button for cart


The tap fires first and page won't change. Slower tap lets load occur. A sync tap? 

On unrelated note, how long does it take you to burn an app like the demo?  

I bet a coworker that you could do one In like a three days and build all your own elements. 

He said I was a fanboy. What can I say. 

Again great job and thanks. 

J

**Comment by frankiefu** [comment]
@jfrazzano Do you mind filing a separate issue on the cart anchor issue, with the steps and browser/device you see the issue?  As with the work building the Shop app.  Thanks for the compliments.  We actually had a few people working on building the app.  The main guys are @blasten and @keanulee.  I would say we built the main part of the app in less than a week.  And then we spent a lot of time in polishing and also fine-tuned it for PWA and coming up with [App Toolbox](https://www.polymer-project.org/1.0/toolbox/).  And now with the App Toolbox, I think we should be able to build the next PWA app much quicker.

**Comment by frankiefu** [comment]
@abdonrd Thanks for filing the issue in paper-icon-button.  Closing this.
