### ISSUE TITLE
Using Roboto font without import it

### ISSUE THREAD

**Issue by abdonrd** [Polymer/shop#34]
Using Roboto font in the [index.hmlt#L30](https://github.com/Polymer/shop/blob/master/index.html#L30), without import it.

**Comment by keanulee** [comment]
Roboto is included in Chrome by default, and we fall back to another font if it's not included in another browser. The reason we don't import the font is because loading an external font blocks layout and leads to poor initial render time.

**Comment by aress31** [comment]
So why not adding the font to the bundle as a static resource instead?
