### ISSUE TITLE
How do I get the shop documentation to work?

### ISSUE THREAD

**Issue by philipbeadle** [Polymer/shop#39]
Doing a polymer serve and going to http://localhost:8080/components/SHOP/ shows no docs or demos.  None of the element files have docs in them which I'm happy to do but I cant figure out how to get any docs page to show.
So what I'd love to see is the demo and docs pages setup showing how to configure it to show docs for at least 2 elements.  Then I'll do the rest.

**Comment by blasten** [comment]
@philipbeadle you should go to `http://localhost:8080/` because it's an app.  Use `http://localhost:8080/components/SHOP/` for components.

**Comment by philipbeadle** [comment]
That doesn't work.  I added a new file called docs.html and set that up with the imports file.  It now shows the docs for the elements.

**Comment by blasten** [comment]
@philipbeadle I see sorry. If you are using the polymer-cli tool, you can cd to an empty directory, run `polymer init` and pick the element template. Also you can check the seed-element https://github.com/PolymerElements/seed-element
