### ISSUE TITLE
If you uncheck "Use different billing address", the ripple stays

### ISSUE THREAD

**Issue by AlexNPavel** [Polymer/shop#41]
On the checkout page (https://shop.polymer-project.org/checkout), if you check the "Use different billing address" under the billing section and then uncheck it later, the dark circle for the ripple effect remains until you click it again.
![polymer-store-glitch](https://cloud.githubusercontent.com/assets/3813031/15808621/f4284762-2b49-11e6-895d-3190cec36ee4.png)

**Comment by keanulee** [comment]
Currently that is the expected behavior since that is the focused state (see https://github.com/Polymer/shop/blob/master/src/shop-checkbox.html#L77).
