### ISSUE TITLE
Can not work with paper-elements together?

### ISSUE THREAD

**Issue by iugo** [Polymer/shop#43]
Shop's styles and paper-elements using two different methods. When add a paper element into a `shop-*.html`, the paper element missing styles.

How do I fix this?

**Comment by abdonrd** [comment]
I think is the same problem: https://github.com/Polymer/app-drawer-template/issues/19

**Comment by frankiefu** [comment]
Issue is in Polymer: https://github.com/Polymer/polymer/issues/3705
