### ISSUE TITLE
Placement of script tags in index.html

### ISSUE THREAD

**Issue by akc42** [Polymer/shop#46]
I was using the shop application as a template to alter my web application into a progressive web app.  I am using the app-header-layout with a app-header that is using the blend-background facility with an image.

When I place my initialization script where the shop has it, near the bottom of the body, I end up with Polymer throwing type errors 
`Uncaught TypeError: Cannot read property '_makeReady' of undefined` at polymer-micro.html:117

If I move the script up to where its put by the polymer cli tool when I initialize the app with an app-drawer-template, ie in the header before the html import of the my-app element these problems go away.

**Comment by frankiefu** [comment]
You may need to make the import `async`, See [here](https://github.com/Polymer/shop/blob/master/index.html#L24).
