### ISSUE TITLE
snackbar should display at any pages

### ISSUE THREAD

**Issue by motss** [Polymer/shop#55]
Is this intended to only show snackbar on `/list` pages?

Step to reproduce:
1. Go to any `/detail` page.
2. Go offline and see no snackbar to notify the user of the current network status.

**Comment by frankiefu** [comment]
Verified this is a bug.

**Comment by ajgoldenwings** [comment]
Also in cart and checkout if page is max-width: 767px for media query.

If you hide the button, you will see the snackbar.

One suggestion is to set bottom: 64px to the snackbar but it will only work if there's a button on the bottom.
