### ISSUE TITLE
Confusion about shop-data-categories properties

### ISSUE THREAD

**Issue by Glowyrm** [Polymer/shop#58]
This concerns the properties of the shop-data-categories component.

 What is the "**items**" property on **category** (the computed value of item is called with category.items as argument to _computeItem)?  Wouldn't this fail (category.items should return undefined if it hasn't been declared yet)? (I tried checking this by creating a ready life-cycle function and logging "items" in category, but then the app failed) 

Thank you for any help on these matters

**Comment by keanulee** [comment]
`<shop-category-data>.category.items` is set here: https://github.com/Polymer/shop/blob/master/src/shop-category-data.html#L115 (i.e. after the products for that category is fetched by XHR). Initially, it is not set (therefore `undefined`, but not an error), and we only fetch the product list if this is the case (see https://github.com/Polymer/shop/blob/master/src/shop-category-data.html#L109).

**Comment by frankiefu** [comment]
@keanulee has answered the question so I am closing it.

**Comment by Glowyrm** [comment]
Thank you @keanulee, good work man :)
