### ISSUE TITLE
Run vulcanize with SHOP made error 

### ISSUE THREAD

**Issue by minhlong139** [Polymer/shop#59]
Hi,

I try to run vulcanize for this orginal project, at root project:

> vulcanize  --inline-scripts --inline-css --strip-comments   src/shop-app.html > src/shop-app-combined.html

=> It run ok, shop-app-combined.html generate successfull. 

After that edit: 
-   `<link rel="import" href="/src/shop-app.html" async> `
to: 
-   `<link rel="import" href="/src/shop-app-combined.html" async>`

ERROR: 
`polymer-micro.html:346 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.(anonymous function) @ polymer-micro.html:346(anonymous function) @ polymer-micro.html:361
polymer-micro.html:67 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a functiondesugar @ polymer-micro.html:67window.Polymer @ polymer-micro.html:54(anonymous function) @ polymer.html:3597(anonymous function) @ polymer.html:3664
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ app-route.html:88
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-category-data.html:44(anonymous function) @ shop-category-data.html:148
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-image.html:46
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-detail.html:208
shop-app-combined.html:8564 Uncaught TypeError: Cannot set property '_scrollTimer' of undefined(anonymous function) @ shop-app-combined.html:8564
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ app-drawer.html:175
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-meta.html:63(anonymous function) @ iron-meta.html:332
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-icon.html:107
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ paper-ripple.html:438(anonymous function) @ paper-ripple.html:757
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ paper-icon-button.html:127
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-localstorage.html:79
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-cart-data.html:25
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-overlay-backdrop.html:62(anonymous function) @ iron-overlay-backdrop.html:166
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-cart-modal.html:109
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-iconset-svg.html:50
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-snackbar.html:62
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-tabs-overlay.html:30
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-tabs.html:38
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-ripple-container.html:29
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-tab.html:48
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-network-warning.html:66
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ shop-cart-item.html:212
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-request.html:23
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ polymer-micro.html:175desugar @ polymer-micro.html:70window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-ajax.html:41
polymer-micro.html:67 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a functiondesugar @ polymer-micro.html:67window.Polymer @ polymer-micro.html:54(anonymous function) @ iron-form.html:66
polymer-micro.html:175 Uncaught TypeError: this._desugarBehaviors is not a function`

**Comment by frankiefu** [comment]
The Shop app is built using the App Toolbox and the PRPL pattern.  Some imports are loaded lazily by calling `importHref`.  It's best to use `polymer-cli` to generate the build.  For more info: https://www.polymer-project.org/1.0/toolbox/server#build-output
