### ISSUE TITLE
Routing is broken.

### ISSUE THREAD

**Issue by kayur** [Polymer/shop#62]
Let's say i'm serving these files with my own webserver at 127.0.0.1:8000, I expect the URI 127.0.0.1:8000/index.html to load the page correctly. It doesn't. Here is the error. 

http://127.0.0.1:8000/src/shop-index.html.html Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by priley86** [comment]
+1, I've run into the same issue serving the `bundled` and `unbundled` directories in [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en). 

I guess a better question is what does `polyserve` do differently, that we are not accounting for when serving?

#23 appears related...

**Comment by keanulee** [comment]
Load `localhost:8000/`, not `localhost:8000/index.html`. The reason why the latter doesn't work is because our router uses the URL path to load an import (e.g. `localhost:8000/list/` loads `shop-list.html`). If you use polymer-cli (or most web servers), the path `/` should resolve to `index.html`.
