### ISSUE TITLE
Typo at CSS

### ISSUE THREAD

**Issue by motss** [Polymer/shop#63]
Typo at line 34 and line 35?

https://github.com/Polymer/shop/blob/master/src/shop-cart-modal.html#L34

```css
-webkit-transform: translate3d(calc(100% - 16px), 0, 0);
transform: translate3d(calc(100% + 16px), 0, 0);
```

Which one is the right one? With plus or minus sign?

**Comment by keanulee** [comment]
Should be `100% + 16px`, since we want to slide the modal to the right by the width of the modal plus its right position (16px). Thanks for the heads up.
