### ISSUE TITLE
Issues with Windows 10 mobile emulation

### ISSUE THREAD

**Issue by OpenNetTools** [Polymer/shop#67]
I tried to install the this demo and trying to run with windows 10 mobile emulation mode on IE edge browser. The hamburger menu is not responding. 

Anyone has seen this issue? or the demo is not supported on windows 10 mobile?

I am a newbie as far as polymer is concerned. Any pointers will be appreciated.

**Comment by keanulee** [comment]
@OpenNetTools I just tried in with Edge on Windows 10 (emulating Windows 10 Mobile) and the menu button seems to toggle the drawer. Can you try this on https://shop.polymer-project.org/?

**Comment by OpenNetTools** [comment]
@keanulee I tried again and it was not working. However, I then installed the real windows 10 mobile emulator and it worked just fine. So I will take it as some settings issue on my IE edge browser.
