### ISSUE TITLE
Add DEMO badge

### ISSUE THREAD

**Issue by frankiefu** [Polymer/shop#68]
![unnamed](https://cloud.githubusercontent.com/assets/116360/17877346/72bcd310-6897-11e6-8e03-7d0f87aaf01b.png)

![unnamed 1](https://cloud.githubusercontent.com/assets/116360/17877348/76e5fc46-6897-11e6-9f05-08da8193e585.png)

**Comment by keanulee** [comment]
@frankiefu We have a few places in the mobile UI that has a button fixed to the bottom and will cover this label. Is it okay to have the label just by the footer, or something that's always visible?

**Comment by frankiefu** [comment]
Having the label just by the footer is fine.
