### ISSUE TITLE
Fix deploy to GitHub Pages

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [Polymer/shop#73]
This project needs changes something like https://github.com/PolymerElements/polymer-starter-kit/pull/905

**Comment by keanulee** [comment]
For Shop we serve the same index.html for all URLs, but GitHub Pages has the restriction that URLs must map to a file at the same path, so it cannot be supported. If you need to use GitHub Pages, you'll need to use hash-based routing, as you suggested (or [redirect from 404.html](https://www.smashingmagazine.com/2016/08/sghpa-single-page-app-hack-github-pages/), but that's a pretty hacky solution).

**Comment by FluorescentHallucinogen** [comment]
@keanulee, the problem is not only in GitHub Pages. Try to deploy Shop to subdirectory on Firebase. The problem is in using absolute paths instead of relative.

Why you closed this issue and added the `wontfix` label?

Is using hash-based routing a bad solution?

**Comment by FluorescentHallucinogen** [comment]
@robdodson, @chuckh, WDYT?

**Comment by oneezy** [comment]
@FluorescentHallucinogen , 

- It's a good solution for GHpages
- It's a bad solution for SEO.

I  believe it would be a bit of working backwards to take that route, although i think it would be a nice thing to have.

You can refer to this SEO issue from the Polymer Starter Kit  where this was talked about in depth: https://github.com/PolymerElements/polymer-starter-kit/issues/367

-----

> **@arthurevans:** I would avoid the hash bangs unless you're using the (deprecated) AJAX Crawling Spec (see https://developers.google.com/webmasters/ajax-crawling/docs/getting-started#overview-of-solution for an overview). This spec was created before the crawler ran javascript on pages, and it relies on your application providing a separate, server-rendered view of your page for the indexer. It doesn't sound like you're doing that, so the hashbangs are probably just confusing things.

> The best thing for indexing is to have full URLs. (www.example.com/path1, not fragments like www.example.com/#!path1).

> Make sure that each page has a unique title. For a SPA, you'll probably need to update this programmatically. For example, the doc site retrieves pages using AJAX, and updates the title when it loads a new page:

> https://github.com/Polymer/docs/blob/master/app/elements/pw-shell.html#L281
