### ISSUE TITLE
bower.json name "SHOP" is invalid, warns on install

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/shop#74]
Bower warns when the package name ("SHOP") is invalid.

```
$ bower --version
1.7.9
$ bower i
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
```

**Comment by FredKSchott** [comment]
@frankiefu @keanulee this is pretty bad, no one on newer bower versions can install and run shop properly without modifying the bower.json name themselves.

**Comment by ebidel** [comment]
Can you use these checkout instructions: https://github.com/Polymer/shop#setup-1

Just tried them and everything works great.

**Comment by FredKSchott** [comment]
Yup, there was an issue with my bower configuration that installed the bower_components in a subfolder where I couldn't find them (see updated issue & comment above). All good now!

I am still getting that warning though, which we may want to keep an eye on / fix if there's no good reason not to.
