### ISSUE TITLE
No 404

### ISSUE THREAD

**Issue by farmer-katherine** [Polymer/shop#79]
For example, if you go to this page, I was expecting a 404:
https://shop.polymer-project.org/sitemap.xml

But I got basically a blank page. I was expecting something more like "oops."

Is it possible to handle 404 routing within the application using web components, instead of configuring it in the web server?

**Comment by TimvdLippe** [comment]
Yes, the iron-pages in shop-app should set the fallback-selection="404" and define small 404 page.
