### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by hayaza** [Polymer/shop#89]
I tried in android browser and it seems that its not supported. I read its only supported by Chrome, IE and FF. But seems that latest opera is supported. 

Anyway to make it work with other browsers?

**Comment by keanulee** [comment]
Hi @hayaza. Shop has the [same browser support as Polymer](https://www.polymer-project.org/1.0/docs/browsers), and Android Browser (i.e. not Chrome) is not officially supported.
