### ISSUE TITLE
Unspecified License

### ISSUE THREAD

**Issue by kishaningithub** [Polymer/shop#94]
Im curious on why a licence file is not present in the project. Can it be assumed MIT ?

**Comment by keanulee** [comment]
Hi @kishaningithub 

Please see the beginning of source files (e.g. https://github.com/Polymer/shop/blob/master/index.html#L2). Basically, all code under the @Polymer, @PolymerLabs, and @PolymerElements orgs are covered under http://polymer.github.io/LICENSE.txt
