### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by denar90** [Polymer/shop#95]
I was playing with perf investigations and found that going from `home` -> `list/mens_outerwear` -> `home` listeners and number nodes are increasing. (I can assume that this problem can be for other pages)

Number of listeners increased form 89 to 130, nodes 1881 -> 2532.

![home - shop - timeline](https://cloud.githubusercontent.com/assets/6231516/19933779/3d3681b4-a11d-11e6-83c8-482f8e6edba9.png)

Also I made a snapshot for current state and new one, repeating `list/mens_outerwear` -> `home` actions. 
It looks like there are a lot of detached nodes which have references to `window`.

![home - shop - snapshot](https://cloud.githubusercontent.com/assets/6231516/19933801/4c1bcdba-a11d-11e6-8c45-e4dec9738c65.png)

P.S. Maybe before fixing this one it make sense to use [drool](https://github.com/samccone/drool) and it's wrapper for polymer - [polymer-drool](https://github.com/samccone/polymer-drool) for testing possible leaks. It requires add `package.json` to project (probably replacing bower).

**Comment by ebidel** [comment]
Here's another profile clicking between "Men's Outerwear" and hitting the back button:

<img width="1162" alt="screen shot 2016-11-02 at 9 15 59 am" src="https://cloud.githubusercontent.com/assets/238208/19937524/e479cda8-a0de-11e6-8091-07c2a73e4b27.png">

Clicking between the "Men's Outerwear" tab and "Ladies Outwear" tabs:

<img width="1155" alt="screen shot 2016-11-02 at 9 18 14 am" src="https://cloud.githubusercontent.com/assets/238208/19937562/fd8b08a2-a0de-11e6-90ad-973622660cbc.png">

**Comment by keanulee** [comment]
This may be related to how we use `this.importHref` on every `_pageChanged` - you can see that the `<head>` is filled with HTML imports for the same file, and each one of those is probably adding a listener for "load" (though at least the XHR request is not repeated since HTML imports are de-duplicate).

**Comment by denar90** [comment]
@ebidel yeah plenty of leaks and @keanulee's solution might fix most of them. Other then that I propose to write some tests to find and fix other possible leaks.

**Comment by frankiefu** [comment]
There is a bug in `Polymer.Base.importHref` which it's not cleaning up the listeners (load/error) when it's trying to import the same file again.  @blasten has a potential fix for this.  He is also looking at the other issue which even on the same list page, switching between the "Men's Outerwear" tab and "Ladies Outwear" tabs causing the node count to grow.

**Comment by blasten** [comment]
This PR should fix the first issue: https://github.com/Polymer/polymer/pull/4124. 

I was trying to repro the second issue: *Clicking between the "Men's Outerwear" tab and "Ladies Outwear"*, and it seems like if you click the trash can to force GC, things drop to normal. cc @ebidel

**Comment by ebidel** [comment]
Yea, if I force GCs things drop (not completely), but reasonable:

<img width="1105" alt="screen shot 2016-11-02 at 5 37 36 pm" src="https://cloud.githubusercontent.com/assets/238208/19952499/141e9e14-a123-11e6-9db8-2ce2fe3707fd.png">

**Comment by blasten** [comment]
yeah. In my test, I went to https://shop.polymer-project.org/list/mens_outerwear  and then clicked on `ladies_outerwear`. Then, I went back and forth between those two pages for a while and eventually stopped back on `mens_outerwear`, forced GC a few times, and went to `ladies_outerwear` one last time. In this test, I don't see a memory leak:

<img width="1239" alt="screen shot 2016-11-03 at 10 24 39 am" src="https://cloud.githubusercontent.com/assets/1410613/19977285/4d15982a-a1b0-11e6-8cea-63bd359d1819.png">

I think the key is to return to state from which the test started, and lastly press the trash can *a few* times.

**Comment by denar90** [comment]
I recorded my profiling in incognito - https://monosnap.com/file/JDfs7ukxcQSO5cpjrNsRCgURfeKJam

Also here [link](https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/5bc597f8b08f3a1288ea637e23e43624/raw/fe1f6f88a13c05e67da25dc3fd4a122fc1162dc5/polymer-shop.memory-leak) to timeline-viawer with my profiling. It's not in incognito mode because of strange issue in Chrome, it's not saving timeline data in incognito, but other than that this result shows that issue with memory leak is still present. Maybe it can be helpful.

**Comment by blasten** [comment]
It might need an update. shop.polymer-project.org is running Polymer `1.4.0`
