### ISSUE TITLE
Service Worker: How to build "Fresh" version of website for each new deployment?

### ISSUE THREAD

**Issue by oneezy** [Polymer/shop#96]
# The Problem

I'm having an issue with a website in production that's serving up old versions of code despite the new and improved deployments.

I'm using the `$ polymer build` command and then the `$ firebase deploy` command to push up changes to Firebase Hosting. After deploy is complete, I navigate to the website only to see the changes not updating:

- **Chrome:** I see the old version of the website first and have to "hard refresh" for the changes to appear.

- **FireFox:** I see the old version of the website first and have to "hard refresh" for the changes to appear.

-----

![image](https://cloud.githubusercontent.com/assets/7369575/20034803/7e97877e-a399-11e6-854b-619582ca5689.png)

-----

# Service Worker workflow?
I'm trying to figure out what the best workflow is for this. I want to set things up so that every time I make a new deploy, the entire site is wiped clean across the inter webs and I'll be 100% sure that existing users will get that newly deployed experience 

> with out having to _hard refresh_ or use _incognito mode_.

## Should I...
- Delete the service worker and deploy the new version without it (bad idea) ?
- Create a "New Project" in the Firebase Console and re-link the custom domain up (tedious) ?
- Find the "magic button" to press inside Firebase Console to reset (does this exist) ?
- Edit the `sw-precache-config.js` file (not sure how) ?
- Handle this in the `$ polymer build` to configure the `sw-precache` (not sure how) ?
- Something awesome that  don't even know about  `¯\_(ツ)_/¯` ?

-----
I know that the _problem_ exists inside the `sw-precache-config.js` file, but I'm unsure if this is where I should be _fixing_ this.

```
module.exports = {
  staticFileGlobs: [
    '/index.html',
    '/manifest.json',
    '/bower_components/webcomponentsjs/webcomponents-lite.min.js',
    '/images/*'
  ],
  navigateFallback: '/index.html',
  navigateFallbackWhitelist: [/^(?!.*\.html$|\/data\/).*/],
  runtimeCaching: [
    {
      urlPattern: /\/data\/images\/.*/,
      handler: 'cacheFirst',
      options: {
        cache: {
          maxEntries: 200,
          name: 'items-cache'
        }
      }
    },
    {
      urlPattern: /\/data\/.*json/,
      handler: 'fastest',
      options: {
        cache: {
          maxEntries: 100,
          name: 'data-cache'
        }
      }
    }
  ]
};

```
-----

The Service Worker is an amazing tool and I definitely want it in my projects. I just need to learn how to tame the beast.

**Comment by frankiefu** [comment]
There is an issue in PSK talks about ways to handle the cache issue: https://github.com/PolymerElements/polymer-starter-kit/issues/806

I am closing this and let's continue the conversation over there.

**Comment by oneezy** [comment]
Thanks @frankiefu , will have a look
