### ISSUE TITLE
Unable to run the shop - see the issue below

### ISSUE THREAD

**Issue by jessicastorm1986** [Polymer/shop#97]
Hello,

I have copied the shop here - c:\users\jessica\pwashop\shop>

and i have install plomer , see here -  https://www.dropbox.com/s/w27cdcsrj61p9gz/Screenshot%202016-11-12%2011.26.35.png?dl=0

when i run polymer serve, the shop is not running, i see just a blank white page with "shop" written, see here - https://www.dropbox.com/s/ftq592nju841gjn/Screenshot%202016-11-12%2011.27.54.png?dl=0

What is the issue, please help.

**Comment by oneezy** [comment]
How did you copy the shop?

Did you `$bower install` the dependencies?

**Comment by oneezy** [comment]
If you have the Polymer CLI tool, you can simply run `$ polymer init` , and choose option "3" for the shop template. This will install the shop app along w/ all dependencies (no need to bower install if you use polymer init).

Then you can run `$ polymer serve` to start it up.

-----

On the other hand, if you have downloaded/ copied/ git cloned the polymer shop repository onto your local machine, you'll always need to run the `$ bower install` command.

**Comment by jessicastorm1986** [comment]
i have downloaded it and unzipped, bower install what ? or i go inside the shop folder and then type bower install command ?

**Comment by oneezy** [comment]
No worries! We've all been there :)

You're going to need to globally install the tool bower on your system, which is a package manager that Polymer uses to install all of it's dependencies.

Inside your Git CMD, write `npm install bower -g` (-g means global)

After install is complete, you'll want to run `bower install` in your Git CMD

This installs all the packages from inside the `bower.json` file that comes with the Polymer Shop. 

After that, run `polymer serve` and your app should work


-----

To learn more about bower, have a look here: 
https://www.youtube.com/watch?v=Vs2wduoN9Ws&t=355s

**Comment by jessicastorm1986** [comment]
worked, let me dive inside, one thing i want to know , what is this using ? material design or ionic  or nothing ?

**Comment by oneezy** [comment]
When you're working w/ the Polymer library and the Polymer-CLI, you're working purely w/ the browser platform and it's native web technology (html/css/js). Polymer library has created similar concepts to use from other frameworks, however you're not required to use these. Ionic is a framework and isn't related to Polymer, and you also don't need to use xamp. Polymer-CLI's `polymer serve` command creates a running server for you on `localhost:8080`. If for any reason you need run on a different port, you should pass it the `-p` flag and list your port number.

Example: `polymer serve -p 9999`

Material design is only a concept, and Polymer has created the [Paper Elements](https://elements.polymer-project.org/browse?package=paper-elements) that demonstrates these ideas, but you aren't in any way enforced to use this (it is good practice though).

There's a few ways to deploy your application, I personally use Firebase (polymer fire).

-----

I'd suggest you spend a few days watching Polycasts on YouTube to get a better idea of how everything works. It will answer many of the questions you have:

https://www.youtube.com/playlist?list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo

**Comment by jessicastorm1986** [comment]
alright i'll watch them, i was wondering as how can i deploy it on my server [will check out polymer fire] and do i need a https or not

**Comment by frankiefu** [comment]
I am closing this. If you think this is an issue in the cli please file an issue there: https://github.com/Polymer/polymer-cli/issues

Thanks.
